services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NDK_VERSION: 23
    volumes:
      - ./rootfs/data:/app/rootfs/data
    ports:
      - "8080:8080"
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    security_opt:
      - seccomp:unconfined
